services:
  - type: web
    name: food-menu-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DB_PATH
        value: /var/data/food_menu.db